In [1]:
import pandas as pd

In [2]:
df_csv = pd.read_csv('disperkim-od_16985_jumlah_produksi_sampah_berdasarkan_kabupatenkota_v3_data.csv')
df_csv

,id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_produksi_sampah,satuan,tahun
0,1,32,JAWA BARAT,3201,KABUPATEN BOGOR,1511.15,TON PER HARI,2015
1,2,32,JAWA BARAT,3202,KABUPATEN SUKABUMI,419.01,TON PER HARI,2015
2,3,32,JAWA BARAT,3203,KABUPATEN CIANJUR,981.41,TON PER HARI,2015
3,4,32,JAWA BARAT,3204,KABUPATEN BANDUNG,1895.94,TON PER HARI,2015
4,5,32,JAWA BARAT,3205,KABUPATEN GARUT,464.74,TON PER HARI,2015
...,...,...,...,...,...,...,...,...
238,239,32,JAWA BARAT,3275,KOTA BEKASI,NaN,TON PER HARI,2023
239,240,32,JAWA BARAT,3276,KOTA DEPOK,NaN,TON PER HARI,2023
240,241,32,JAWA BARAT,3277,KOTA CIMAHI,NaN,TON PER HARI,2023
241,242,32,JAWA BARAT,3278,KOTA TASIKMALAYA,NaN,TON PER HARI,2023
242,243,32,JAWA BARAT,3279,KOTA BANJAR,NaN,TON PER HARI,2023

In [3]:
df_csv.isnull()

,id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_produksi_sampah,satuan,tahun
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
238,False,False,False,False,False,True,False,False
239,False,False,False,False,False,True,False,False
240,False,False,False,False,False,True,False,False
241,False,False,False,False,False,True,False,False
242,False,False,False,False,False,True,False,False

In [4]:
proc_df = df_csv.dropna()

In [5]:
print("No.1\n")
print("Data Produksi Sampah Provinsi Jawa Barat")
filter_data = proc_df.loc[df_csv['nama_provinsi'] == 'JAWA BARAT', ['nama_kabupaten_kota', 'jumlah_produksi_sampah', 'tahun']]
df_no1 = filter_data
df_no1

No.1

Data Produksi Sampah Provinsi Jawa Barat

    nama_kabupaten_kota  jumlah_produksi_sampah  tahun
0       KABUPATEN BOGOR                 1511.15   2015
1    KABUPATEN SUKABUMI                  419.01   2015
2     KABUPATEN CIANJUR                  981.41   2015
3     KABUPATEN BANDUNG                 1895.94   2015
4       KABUPATEN GARUT                  464.74   2015
..                  ...                     ...    ...
184         KOTA BEKASI                 1500.77   2021
185          KOTA DEPOK                 1418.87   2021
186         KOTA CIMAHI                  193.36   2021
187    KOTA TASIKMALAYA                  295.87   2021
188         KOTA BANJAR                   60.29   2021

[189 rows x 3 columns]

In [6]:
print("No.2\n")
print("Masukkan tahun untuk menampilkan total produksi sampah pada tahun tersebut")
tahun_in = int(input("Anda akan menapilkan data tahun: "))
print(f"Anda memilih tahun {tahun_in}\n")

total_prod = 0
for index, row in filter_data.iterrows():
    if row['tahun'] == tahun_in:
        total_prod += row['jumlah_produksi_sampah']

print(f"Total produksi sampah di seluruh Kabupaten/Kota di Jawa Barat untuk tahun {tahun_in} adalah {total_prod:.2f} ton.")

df_no2 = pd.DataFrame({
    'Tahun': [tahun_in],
    'Total Produksi Sampah (ton)': [total_prod]
})

No.2

Masukkan tahun untuk menampilkan total produksi sampah pada tahun tersebut
Anda memilih tahun 2018

Total produksi sampah di seluruh Kabupaten/Kota di Jawa Barat untuk tahun 2018 adalah 22772.92 ton.

In [7]:
print("No.3\n")
print("Jumlah Data Pertahun:")
jum_pertahun = {}

for index, row in proc_df.iterrows():
    if row['tahun'] in jum_pertahun:
        jum_pertahun[row['tahun']] += 1
    else:
        jum_pertahun[row['tahun']] = 1

for tahun, jumlah in jum_pertahun.items():
    print(f"Tahun {tahun} memiliki data sebesar {jumlah} data.")
    
data_pertahun = [
    {'Tahun': tahun, 'Jumlah Data': jumlah}
    for tahun, jumlah in jum_pertahun.items()
]
df_no3 = pd.DataFrame(data_pertahun)

No.3

Jumlah Data Pertahun:
Tahun 2015 memiliki data sebesar 27 data.
Tahun 2016 memiliki data sebesar 27 data.
Tahun 2017 memiliki data sebesar 27 data.
Tahun 2018 memiliki data sebesar 27 data.
Tahun 2019 memiliki data sebesar 27 data.
Tahun 2020 memiliki data sebesar 27 data.
Tahun 2021 memiliki data sebesar 27 data.

In [8]:
print("No.4\n")
print("Jumlah Data Perkabupaten/Kota:")
jum_perkab = {}

for index, row in proc_df.iterrows():
    if row['nama_kabupaten_kota'] not in jum_perkab:
        jum_perkab[row['nama_kabupaten_kota']] = {}
    if row['tahun'] in jum_perkab[row['nama_kabupaten_kota']]:
        jum_perkab[row['nama_kabupaten_kota']][row['tahun']] += 1
    else:
        jum_perkab[row['nama_kabupaten_kota']][row['tahun']] = 1

for daerah, data in jum_perkab.items():
    print(f"Kabupaten {daerah}:")
    for tahun, jumlah in data.items():
        print(f" - Tahun {tahun}: {jumlah} data")
        
data_perkab = [
    {'Kabupaten/Kota': daerah, 'Tahun': tahun, 'Jumlah Data': jumlah}
    for daerah, data in jum_perkab.items()
    for tahun, jumlah in data.items()
]

df_no4 = pd.DataFrame(data_perkab)

No.4

Jumlah Data Perkabupaten/Kota:
Kabupaten KABUPATEN BOGOR:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN SUKABUMI:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN CIANJUR:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN BANDUNG:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN GARUT:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN TASIKMALAYA:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN CIAMIS:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN KUNINGAN:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN CIREBON:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN MAJALENGKA:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN SUMEDANG:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN INDRAMAYU:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN SUBANG:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN PURWAKARTA:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN KARAWANG:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN BEKASI:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN BANDUNG BARAT:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KABUPATEN PANGANDARAN:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA BOGOR:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA SUKABUMI:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA BANDUNG:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA CIREBON:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA BEKASI:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA DEPOK:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA CIMAHI:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA TASIKMALAYA:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data
Kabupaten KOTA BANJAR:
 - Tahun 2015: 1 data
 - Tahun 2016: 1 data
 - Tahun 2017: 1 data
 - Tahun 2018: 1 data
 - Tahun 2019: 1 data
 - Tahun 2020: 1 data
 - Tahun 2021: 1 data

In [9]:
with pd.ExcelWriter("hasil/hasil_produksi_sampah.xlsx") as writer:
    df_no1.to_excel(writer, sheet_name="No1_Produksi_Sampah_Jawa_Barat", index=False)
    df_no2.to_excel(writer, sheet_name=f"No2_Total_Produksi_Sampah_Jawa_Barat_Tahun_{tahun_in}", index=False)
    df_no3.to_excel(writer, sheet_name="No3_Jumlah_Data_Pertahun", index=False)
    df_no4.to_excel(writer, sheet_name="No4_Jumlah_Data_Perkabupaten", index=False)

c:\Users\ppfat\anaconda3\envs\MachineLearning\Lib\site-packages\openpyxl\workbook\child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")

In [10]:
df_no1.to_csv("hasil/No1_produksi_sampah_jawa_barat.csv", index=False)
df_no2.to_csv(f"hasil/No2_total_produksi_sampah_jawa_barat_tahun_{tahun_in}.csv", index=False)
df_no3.to_csv("hasil/No3_jumlah_data_pertahun.csv", index=False)
df_no4.to_csv("hasil/No4_jumlah_data_perkabupaten.csv", index=False)

In [11]:
jum_pertahun

{2015: 27, 2016: 27, 2017: 27, 2018: 27, 2019: 27, 2020: 27, 2021: 27}

In [12]:
jum_perkab

{'KABUPATEN BOGOR': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN SUKABUMI': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN CIANJUR': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN BANDUNG': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN GARUT': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN TASIKMALAYA': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN CIAMIS': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN KUNINGAN': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN CIREBON': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN MAJALENGKA': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN SUMEDANG': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN INDRAMAYU': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN SUBANG': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN PURWAKARTA': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN KARAWANG': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN BEKASI': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN BANDUNG BARAT': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KABUPATEN PANGANDARAN': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KOTA BOGOR': {2015: 1, 2016: 1, 2017: 1, 2018: 1, 2019: 1, 2020: 1, 2021: 1},
 'KOTA SUKABUMI': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KOTA BANDUNG': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KOTA CIREBON': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KOTA BEKASI': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KOTA DEPOK': {2015: 1, 2016: 1, 2017: 1, 2018: 1, 2019: 1, 2020: 1, 2021: 1},
 'KOTA CIMAHI': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KOTA TASIKMALAYA': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1},
 'KOTA BANJAR': {2015: 1,
  2016: 1,
  2017: 1,
  2018: 1,
  2019: 1,
  2020: 1,
  2021: 1}}

In [13]:
# Tugas Dataframe

# 1. Dengan menggunakan pustaka pandas di Python, buatlah sebuah DataFrame dari data jumlah produksi sampah berdasarkan Kabupaten/Kota di Jawa Barat.
#       Pastikan kolom-kolomnya menyertakan nama Kabupaten/Kota, jumlah produksi sampah (dalam ton), dan tahun pencatatan.

# 2. Dari DataFrame yang telah dibuat, hitunglah total produksi sampah di seluruh Kabupaten/Kota di Jawa Barat untuk tahun tertentu. Tampilkan hasilnya.

# 3. Jumlahkan Data Pertahun

# 4. Jumlahkan data per Kota/Kabupaten per tahun

# Ketentuan : 
# Gunakan Itterrows untuk setiap soal kecuali no 1
# Export hasil akhir menjadi CSV dan Excel
# Buatkan Video penjelasan dan masukan link kedalam README github
# Upload semua hasil pengerjaan ke Github
# Kirim berupa PDF yang berisi link github ke elarning